# Users schema

# --- !Ups

CREATE TABLE MEMBER(
  MEMBER_ID    INT         PRIMARY KEY NOT NULL,
  MEMBER_NAME  VARCHAR(255) NOT NULL,
  MD5          VARCHAR(255) NOT NULL,
  REALNAME     VARCHAR(255) NOT NULL,
  EMAIL        VARCHAR(255) NOT NULL,
  COUNTRY      VARCHAR(255) NOT NULL,
  COMPANY      VARCHAR(255),
  TITLE        VARCHAR(255),
  STUDENT_UNTIL DATE,
  PROFESSION   VARCHAR(255)
);

CREATE TABLE ACTIVITY(
  MEMER_ID     INT         REFERENCES MEMBER(MEMBER_ID) NOT NULL,
  TIME_FROM    DATE        NOT NULL,
  TIME_TO      DATE        NOT NULL,
  ACCOUNT_TYPE VARCHAR(255) NOT NULL,
  AMOUNT_PAID  VARCHAR(255)
);

CREATE TABLE INFO(
  ABBREV       VARCHAR(255) PRIMARY KEY NOT NULL,
  TITLE        VARCHAR(255) NOT NULL,
  LANGUAG      VARCHAR(255) NOT NULL,
  AUTHORLASTNAME  VARCHAR(255),
  AUTHORFIRSTNAME VARCHAR(255),
  YEARR        INT,
  PUBLISHER    VARCHAR(255),
  EDITION      INT,
  ACCESS       VARCHAR(255)
);

# --- !Downs

DROP TABLE ACTIVITY;
DROP TABLE MEMBER;

DROP TABLE INFO;
