# --- !Ups

ALTER TABLE MEMBER ADD LASTSEEN VARCHAR(255);
ALTER TABLE MEMBER ADD NUMBEROFLOGINS INT DEFAULT 0;

# --- !Downs

ALTER TABLE MEMBER DROP LASTSEEN;
ALTER TABLE MEMBER DROP NUMBEROFLOGINS;
