# Users schema

# --- !Ups

CREATE TABLE PASSWORDCHANGEREQUEST(
  ID           VARCHAR(255) PRIMARY KEY NOT NULL,
  DATE_        VARCHAR(287) NOT NULL,
  MEMBER_ID    INT NOT NULL
);

# --- !Downs

DROP TABLE PASSWORDCHANGEREQUEST;