# ################################################################
# https://www.playframework.com/documentation/latest/Configuration
# https://www.playframework.com/documentation/2.6.x/Configuration
# ################################################################

# ################################################################
# CSRF Configuration
# ################################################################
play.modules.enabled += "play.filters.csrf.CSRFModule"
play.filters.enabled += "play.filters.csrf.CSRFFilter"

# The cookie Play sends to the browser (readable by ScalaJS)
play.filters.csrf.cookie.name = "csrfCookie"
play.filters.csrf.cookie.secure = true
play.filters.csrf.cookie.httpOnly = false  # MUST be false so getDocumentCsrfCookie() can read it

# Tell Play exactly what header name your ScalaJS SPA is sending
# (Matches your HeaderFields.csrfToken.toString() value)
play.filters.csrf.header.name = "Csrf-Token"

# ################################################################
# Session Configuration
# ################################################################
play.http.session.secure = true
play.http.session.sameSite = "strict"

# CRITICAL SECURITY STEP: Prevent JavaScript/XSS from stealing the User ID session cookie
play.http.session.httpOnly = true

# Apparently, this is deprecated, and we set the policy in apache2.conf anyway
# 'null' means to not set this header at all here.
play.filters.headers.contentSecurityPolicy = null

play.http.secret.key = ${OOREP_APP_SECRET}  # https://www.playframework.com/documentation/2.7.x/ApplicationSecret

play.modules.enabled += "play.api.db.DBModule"
play.modules.enabled += "play.api.db.HikariCPModule"

play.http.parser.maxMemoryBuffer=20MB
play.http.parser.maxDiskBuffer=20MB

play.filters.hosts {
  # Allow requests to example.com, its subdomains, and localhost:9000.
  allowed = ["localhost", "."${?OOREP_APP_DOMAIN}]
}

play.db {
  # The combination of these two settings results in "db.default" as the default JDBC pool:
  config = "db"
  default = "default"

  # Play uses HikariCP as the default connection pool.  You can override settings by changing the prototype:
  # cf. https://stackoverflow.com/questions/49075152/conflict-between-hikari-quill-and-postgres-in-the-conf-file-for-play-2-6
  prototype {
    username = null
    password = null

    hikaricp {
      minimumIdle = 4
      maximumPoolSize = 10
    }
  }
}

db.default {
  driver = org.postgresql.Driver
  username = ${?OOREP_DB_USER}
  password = ${?OOREP_DB_PASS}
  database = ${?OOREP_DB_NAME}
  host = ${?OOREP_DB_HOST}
  portNumber = ${?OOREP_DB_PORT}
  connectionTimeout = 30000
  url = "jdbc:postgresql://"${?OOREP_DB_HOST}":"${OOREP_DB_PORT}"/"${?OOREP_DB_NAME}
}

play.evolutions.db.default.autoApply = true
