image: eclipse-temurin:17

services: 
  - postgres:11

variables:
  SBT_VERSION: "1.9.7"
  OOREP_DB_PASS: test
  OOREP_DB_HOST: postgres
  OOREP_DB_PORT: 5432
  OOREP_APPLICATION_HOST: http://localhost:9000
  OOREP_APPLICATION_SECRET: test
  POSTGRES_DB: oorep
  POSTGRES_USER: oorep_user
  POSTGRES_PASSWORD: test
  PGPASSWORD: test

before_script:
  - apt-get update -y
  - apt-get install -y zip unzip
  - wget https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.zip
  - unzip sbt-${SBT_VERSION}.zip

build:
  script:
    - ./sbt/bin/sbt ++2.13.12 compile
    - ./sbt/bin/sbt ++2.13.12 dist

# Testing currently only works from within IntelliJ.
# 
# test:
#   script:
#     - sbt ++2.13.1 test
