CREATE TABLE USERS(
  USER_ID      INT         PRIMARY KEY NOT NULL,
  USER_NAME    VARCHAR(20) NOT NULL,
  REALNAME     VARCHAR(30) NOT NULL,
  EMAIL        VARCHAR(80) NOT NULL,
  COUNTRY      VARCHAR(80) NOT NULL,
  COMPANY      VARCHAR(80),
  TITLE        VARCHAR(8),
  STUDENT_UNTIL DATE,
  PROFESSION   VARCHAR(80)
);

CREATE TABLE ACTIVITIES(
  USER_ID      INT         REFERENCES USERS(USER_ID) NOT NULL,
  TIME_FROM    DATE        NOT NULL,
  TIME_TO      DATE        NOT NULL,
  ACCOUNT_TYPE VARCHAR(80) NOT NULL,
  AMOUNT_PAID  VARCHAR(80)
);
